version: "3.7"

services:
  hackforgood-database:
    image: mongo
    restart: always
    container_name: hackforgood-database
    ports:
      - 127.0.0.1:27057:27017
    volumes:
      - "./database/:/data/db:z"
    networks:
      - hackforgood-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bruno
      - MONGO_INITDB_ROOT_PASSWORD=71bc66fa866a67909a28e3bbbc1e5d69

  hackforgood-api:
    container_name: hackforgood-api
    restart: always
    ports:
      - 8000:3000
    depends_on:
      - hackforgood-database
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    # links:
    #     - hackforgood-statsd:hackforgood-statsd
    networks:
      - hackforgood-network
    environment:
      - PROD=true
      - MONGODB=mongodb://bruno:71bc66fa866a67909a28e3bbbc1e5d69@hackforgood-database:27057/hackforgood-database?authSource=admin

  hackforgood-fake:
    container_name: hackforgood-fake
    restart: always
    ports:
      - 3005:3000
    depends_on:
      - hackforgood-database
    build:
      context: ./fake-detector
      dockerfile: Dockerfile
    # links:
    #     - hackforgood-statsd:hackforgood-statsd
    networks:
      - hackforgood-network

networks:
  hackforgood-network:
